.env.example
.gitignore
BASELINE.md
arnesis/__init__.py
arnesis/application/__init__.py
arnesis/application/bootstrap.py
arnesis/application/camera_connection_service.py
arnesis/application/camera_management_service.py
arnesis/application/configuration_service.py
arnesis/application/group_management_service.py
arnesis/application/inference_orchestration_service.py
arnesis/application/model_registry_service.py
arnesis/application/processing_profile_service.py
arnesis/application/processing_service.py
arnesis/application/realtime_processing_service.py
arnesis/application/roi_service.py
arnesis/core/__init__.py
arnesis/core/database.py
arnesis/core/database_settings.py
arnesis/domain/__init__.py
arnesis/domain/entities.py
arnesis/infrastructure/__init__.py
arnesis/infrastructure/database.py
arnesis/infrastructure/repositories.py
arnesis/infrastructure/rtsp_endpoint.py
arnesis/processing/__init__.py
arnesis/processing/camera_capture.py
arnesis/processing/camera_pipeline.py
arnesis/processing/camera_runtime.py
arnesis/processing/camera_session.py
arnesis/processing/cuda_device.py
arnesis/processing/cuda_model_manager.py
arnesis/processing/detection_worker.py
arnesis/processing/frame_buffer.py
arnesis/processing/gpu_capacity_manager.py
arnesis/processing/group_session.py
arnesis/processing/inference_group_engine.py
arnesis/processing/inference_result.py
arnesis/processing/latest_frame_queue.py
arnesis/processing/performance_classifier.py
arnesis/processing/processing_runtime.py
arnesis/processing/result_buffer.py
arnesis/processing/roi_assignment.py
arnesis/processing/tracking_service.py
arnesis/processing/visualization_renderer.py
arnesis/ui/__init__.py
arnesis/ui/camera_manager_dialog.py
arnesis/ui/controller_app.py
arnesis/ui/controller_app_before_modern_ui.py
arnesis/ui/group_manager_view.py
arnesis/ui/model_registry_view.py
arnesis/ui/modern_data_grid.py
arnesis/ui/processing_profile_view.py
arnesis/ui/realtime_processing_view.py
arnesis/ui/roi_editor_view.py
arnesis/ui/theme.py
arnesis/ui/ux_messages.py
legacy_reference/SHA256SUMS.txt
legacy_reference/arnesis_legacy.py
requirements.lock.txt
run_arnesis.py
tests/__init__.py
tests/test_latest_frame_queue.py
tests/test_model_registry_package.py
tests/test_on_demand_preview_contract.py
tests/test_on_demand_preview_logic.py
tests/test_preview_bridge.py
tests/test_preview_complete_fix.py
tests/test_preview_frame_cache.py
tests/test_preview_frame_hotfix_v2.py
tests/test_realtime_cards_ui.py
tests/test_realtime_controller_ui.py
tests/test_realtime_multigroup_dashboard.py
tests/test_realtime_preview_contract.py
tests/test_realtime_processing_complete_fix.py
tests/test_realtime_processing_service.py
tests/test_rtsp_error_classification.py
